language: cpp
dist: trusty
sudo: false

os: linux

git:
  depth: 1

env:
  global:
    - secure: |-
        a1eovNn4uol9won7ghr67eD3/59oeESN+G9bWE+ecI1V6yRseG9whniGhIpC/YfMW/Qz5I
        5sxSmFjaw9bxCISNwUIrL1O5x2AmRYTnFcXk4dFsUvlZg+WeF/aKyBYCNRM8C2ndbBmtAO
        o1F2EwFbiso0EmtzhAPs19ujiVxkLn4=

matrix:
  include:
    - env: BUILD=Doc
      sudo: required

script:
  - support/travis-build.py
